service: vaccine-notifier

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  notifyRegistration:
    handler: notify.lambda
    events:
      - http: 
          path: '/notify'
          method: POST
          cors: true 
  getCodes:
    handler: codes.lambda
    events:
      - http:
          path: '/codes'
          method: GET 
          cors: true 

plugins:
  - serverless-offline