service: vaccine-notifier

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-south-1

functions:
  notifyRegistration:
    cors: true
    handler: notify.lambda
    events:
      - http: 'POST /notify'
  getCodes:
    cors: true
    handler: codes.lambda
    events:
      - http: 'GET /codes'

plugins:
  - serverless-offline