service: vaccine-notifier

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1

functions:
  notifyRegistration:
    handler: src/handlers/notifyRegistration.lambda
    environment:
      MONGO_USERNAME: ${env:MONGO_USERNAME}
      MONGO_PASSWORD: ${env:MONGO_PASSWORD}
    events:
      - http: 
          path: '/notify'
          method: POST
          cors: true 
  notify:
    handler: src/handlers/notify.lambda
    environment:
      MONGO_USERNAME: ${env:MONGO_USERNAME}
      MONGO_PASSWORD: ${env:MONGO_PASSWORD}
    events:
      - schedule: rate(6 hours)
  getCodes:
    handler: src/handlers/codes.lambda
    events:
      - http:
          path: '/codes'
          method: GET 
          cors: true 

plugins:
  - serverless-offline